export const ADD_COMPLAINT = "ADD_COMPLAINT";
export const UPDATE_COMPLAINT = "UPDATE_COMPLAINT";
export const UPDATE_COMMENT = "UPDATE_COMMENT";
export const ADD_COMMENT = "ADD_COMMENT";
export const REMOVE_COMMENT = "REMOVE_COMMENT";
export const REMOVE_COMPLAINT = "REMOVE_COMPLAINT";
export const UPDATE_ACCOUNT_STATUS = "UPDATE_ACCOUNT_STATUS";
